package com.virtusa.societyfm.dto;

import lombok.Builder;
import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;
import java.util.Date;
import java.util.UUID;

@Getter
@Setter
@Builder
public class ActivityDTO {

    private UUID activityID;
    private String description;
    private Date date;
    private BigDecimal cost;
    private String activityType;

    // Constructor is omitted

    // Getter, Setter, and Builder methods are generated by Lombok
}
