package com.virtusa.societyfm.dto;

import lombok.Builder;
import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;
import java.util.Date;
import java.util.UUID;

@Getter
@Setter
@Builder
public class DelayedPaymentReportDTO {

    private UUID reportID;
    private UUID familyID;
    private Date lastPaymentDate;
    private BigDecimal amountDue;
    private BigDecimal fineAmount;

    // Constructor is omitted

    // Getter, Setter, and Builder methods are generated by Lombok
}