package com.virtusa.societyfm.dto;

import com.virtusa.societyfm.enums.Month;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;
import java.util.Date;
import java.util.UUID;

@Getter
@Setter
@Builder
public class InwardPaymentReportDTO {

    private UUID reportID;
    private Date paymentDate;
    private UUID familyID;
    private BigDecimal amountPaid;
    private Month month;
    private Integer year;

    // Constructor is omitted

    // Getter, Setter, and Builder methods are generated by Lombok
}
