package com.virtusa.societyfm.dto;

import com.virtusa.societyfm.entities.Family;
import com.virtusa.societyfm.enums.Month;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.UUID;

@Getter
@Setter
@Builder
public class MonthlyMaintenanceDTO {

    private UUID maintenanceID;
    private Family familyID;
    private Month month;
    private Integer year;
    private BigDecimal amountPaid;
    private LocalDate paymentDate;

    // Constructor is omitted

    // Getter, Setter, and Builder methods are generated by Lombok
}
