package com.virtusa.societyfm.dto;

import com.virtusa.societyfm.entities.SocietyUser;
import com.virtusa.societyfm.enums.ApprovalStatus;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;
import java.util.Date;
import java.util.UUID;

@Getter
@Setter
@Builder
public class OutwardPaymentDTO {

    private UUID paymentID;
    private String description;
    private BigDecimal amount;
    private Date paymentDate;
    private SocietyUser checkerID;
    private ApprovalStatus approvalStatus;

    // Constructor is omitted

    // Getter, Setter, and Builder methods are generated by Lombok
}
