package com.virtusa.societyfm.dto;

import lombok.Builder;
import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;
import java.util.UUID;

@Getter
@Setter
@Builder
public class YearlySpendingReportDTO {

    private UUID reportID;
    private Integer year;
    private BigDecimal totalSpending;

    // Constructor is omitted

    // Getter, Setter, and Builder methods are generated by Lombok
}
